#!/bin/bash

nslookup slash16.org | grep Server | awk '{print $2}'

# 'nslookup slash16.org' gets the information on slash16.org domain
# 'grep Server' gets the server line
# 'awk {print $2}' reads the 2nd thing on the line so skips 'Server'
